### ISSUE TITLE
Future Progress?

### ISSUE THREAD

**Issue by GitLang** [maakbaas/mbldc#1]
Hi there. Do you think this is going any further please?. I think it has the potential to be a good ESC. I have migrated the last software  release to STM32CubeIDE 1.12.0 and it's compiling 0 errors and 0 warnings. Has to be a good starting point, have you done any more that could be uploaded please?. I have to change the hardware from the DRV8305PHP to the  DRV8353RS or DRV8353RH as I need a 12s or 13s ESC, and at 100Amps.

**Comment by maakbaas** [comment]
Hi, this project is shared for reference only. I will not be able to give support, or provide any timelines for future updates.
